### ISSUE TITLE
Use with Software Defined Radio like RTL2838?

### ISSUE THREAD

**Issue by petterreinholdtsen** [wirepas/gateway#116]
What would be needed to get this gateway software working with a software defined radio like the USB dongles based on RTL2838?  Is the protocol spesification available to make it possible to read the packages using GNU Radio?

**Comment by GwendalRaoul** [comment]
This gateway software is radio agnostics. It just needs a radio chip connected through UART and running the Wirepas stack and Dual Mcu protocol.
But there is no Wirepas porting for RTL2838.

**Comment by petterreinholdtsen** [comment]
[Gwendal]
> This gateway software is radio agnostics. It just needs a radio chip
> connected through UART and running the Wirepas stack and Dual Mcu
> protocol.  But there is no Wirepas porting for RTL2838.

Right.

What about running the Wirepas stack and Dual Mcu protocol in userspace,
similar to how <URL: https://github.com/ptrkrysik/gr-gsm > and
<URL: https://github.com/merbanan/rtl_433/ >, in other word run it on
Linux, not the individual radio chip?  Is it possible?  Can the gateway
talk to such user space implementation talking to a RTL 2838?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by PFigs** [comment]
Hi @petterreinholdtsen !

I believe our Wirepas stack could run in user space level through emulation (QEMU). However it is something we haven't put effort into. We are only targeting certain radio chips that are most commonly used in the industry. 

As @GwendalRaoul mentioned, the gateway implementation is not bound by a specific radio chip. The gateway software in this repository only handles data translation from/to a UART to/from a MQTT broker. 

The dual mcu frames are translated by the [sink service](https://github.com/wirepas/gateway/tree/master/sink_service) through our [c-mesh-api library](https://github.com/wirepas/c-mesh-api). The c-mesh-api library could in fact be extended to acquire frames from any other interface.

The inbound/outbound mqtt messages are handled by the [transport service](https://github.com/wirepas/gateway/tree/master/python_transport).

**Comment by petterreinholdtsen** [comment]
Thank you very much for the information.  Just to be sure, if I wanted to test the Wirepas stack in qemu, where can I find the code?  I take it from your description that the output from the Wirepass stack is 'dual mcu frames'.  Is this correct?

**Comment by PFigs** [comment]
The Wirepas stack code is closed source. Our licensees have access to a binary, but not the full source.

You can reach out to our sales department through info(at)wirepas.com.
