### ISSUE TITLE
Event id: Help debugging

### ISSUE THREAD

**Issue by GwendalRaoul** [wirepas/gateway#189]
In order to debug what happens at the broker level and especially if messages are dropped, event unique id should be incremented instead of randomly generated.
The API only requires a unique id so an incremented counter is fine.

As it is for debug purpose mainly, it will be chosen by a transport parameter to still use random generated id by default.
Random ids is better especially in case of reboot of the service.

**Comment by ErkkiSalonenW** [comment]
>still use random generated.. 

Solution where for example last bytes are incrementing works also if this simplifies design.

Thanks in advance!
